name: Build and Push Docker to ECR

on:
  push:
    branches:
      - main  
  #workflow_dispatch:  
  #schedule:
  #- cron: '0 18 * * *' # 2:00 AM MALAYSIA TIME

permissions:
  contents: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 022499009488.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t electforecast-web .

    - name: Tag Docker image
      run: docker tag electforecast-web:latest 022499009488.dkr.ecr.us-east-1.amazonaws.com/electforecast/web:latest

    - name: Push Docker image to Amazon ECR
      run: docker push 022499009488.dkr.ecr.us-east-1.amazonaws.com/electforecast/web:latest
