name: Data Extraction

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 1 * * *'  # Runs at 1 AM UTC every day

jobs:
  data_extraction:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Handle ~BROMIUM if it exists
        run: |
          if [ -e "~BROMIUM" ]; then
            echo "Skipping further steps because ~BROMIUM exists."
            exit 0  # Exit early, skipping remaining steps
          else
            echo "~BROMIUM does not exist, continuing normally"
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.10

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libpq-dev libjemalloc-dev dbus-python python3-gi gir1.2-gtk-3.0 \
            python3-distro-info python3-secretstorage python3-keyring \
            python3-apt python3-pip ubuntu-advantage-tools ufw \
            unattended-upgrades

      - name: Update pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Remove problematic packages from requirements_linux.txt before installation
          sed -i '/distro-info==1.1/d' requirements_linux.txt
          sed -i '/dbus-python==1.2.18/d' requirements_linux.txt
          python -m pip install -r requirements_linux.txt

      - name: Run extraction script
        env:
          REDSHIFT_REGION: ${{ secrets.REDSHIFT_REGION }}
          REDSHIFT_WORKGROUP: ${{ secrets.REDSHIFT_WORKGROUP }}
        run: python scripts/extract_data.py

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs/
