name: ML Part 1

on:
  push:
    branches:
      - main 
  schedule:
    - cron: "0 18 * * *" # Runs daily at 18:00 UTC
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Grants write permission to commit and push changes

jobs:
  preprocess:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.10" # Adjust to match your script's Python version

    - name: Upgrade System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make liblapack-dev libblas-dev gfortran

    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements_linux.txt
      
    - name: Run Preprocessing Script
      run: |
        python3 scripts/ml_part_1.py
      env:
        PYTHONUNBUFFERED: 1 # Ensures real-time output in logs
    
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/merge/allyears.csv
        git diff --cached --exit-code || git commit -m "Update with daily preprocessing results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify success
      if: success()
      run: echo "🎉 ML 1 completed successfully!"

        # Step 9: Notify failure
    - name: Notify failure
      if: failure()
      run: echo "❌ ML 1 failed. Check logs for details."

