name: ML Part 1

on:
  push:
    branches:
      - main 
  schedule:
    - cron: "0 18 * * *"  # 2:00 AM MALAYSIA TIME  
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  preprocess:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install System-Level Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          build-essential \
          g++ \
          gcc \
          swig \
          cmake \
          python3-dev \
          python3-pip \
          libopenblas-dev \
          liblapack-dev \
          libatlas-base-dev \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libcurl4-openssl-dev \
          libhdf5-dev \
          libgfortran5 \
          libgomp1

    - name: Upgrade Python Tools
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
    - name: Install Core ML Libraries
      run: |
        echo "🔍 Installing core ML libraries..."
        pip install --no-cache-dir -r requirements_linux.txt --verbose
      
    - name: Check for Dependency Conflicts
      run: |
        python3 -m pip check || exit 1

    - name: Install Stan via CmdStanPy
      run: |
        n=0
        until [ "$n" -ge 5 ]
        do
          python3 -m cmdstanpy.install_cmdstan --version latest && break
          n=$((n+1))
          echo "Retrying in $((2**n)) seconds..."
          sleep $((2**n))
        done
        if [ "$n" -ge 5 ]; then
          echo "❌ CmdStanPy installation failed after 5 attempts."
          exit 1
        fi

    - name: Test Dependency Installation
      run: |
        python3 -c "import pandas, pycaret, numpy, sklearn, tensorflow, darts, pyod, prophet, statsforecast"
        
        
    - name: Debug Installed Packages
      run: |
        echo "🔍 Listing installed pip packages..."
        python3 -m pip list
    

    - name: Check Dependency Tree
      run: |
        python3 -m pip install pipdeptree
        pipdeptree
  
    - name: Run Preprocessing Script
      run: |
        python3 scripts/ml_part_1.py
      env:
        PYTHONUNBUFFERED: 1 
        LOG_LEVEL: DEBUG

    - name: Debug Training Script Logs
      if: failure()
      run: |
        echo "⚠️ Command failed. Debugging..."
        tail -n 50 /var/log/syslog || echo "No syslog available."

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add data/merge/allyears.csv
        git diff --cached --exit-code
        git commit -m "Update with daily preprocessing results at $(date -u '+%Y-%m-%d %H:%M:%S') UTC" || echo "Nothing to commit."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify Completion
      if: always()
      run: |
          if [ $? -eq 0 ]; then
            echo "🎉 Workflow completed successfully!"
          else
            echo "❌ Workflow failed. Check logs for details."
          fi
  